language: c

compiler:
  - gcc
  - clang

# Settings to try
env:
  matrix:
    - BUILD_SYSTEM=autotools
    - BUILD_SYSTEM=cmake

before_install:

  - sudo apt-get install automake libtool flex
  - sudo apt-get install libxml2 libxml2-dev

  # configure cpan, no waiting for user input
  - (echo y;echo o conf prerequisites_policy follow;echo o conf commit)| sudo cpan
  - sudo cpan -i XML::LibXML

script:
  - bison --version
  - flex --version
  - $CC --version
  - which $CC
  # workaround clang not system wide, fail on sudo make install
  - export CC=`which $CC`

  - case $BUILD_SYSTEM in
      autotools)
        ./bootstrap.sh &&
        ./configure --enable-maintainer-mode --prefix=/usr &&
        find . && make V=1 &&
        sudo make install
        ;;
      cmake)
        mkdir build && cd build &&
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DUSE_MAINTAINER_MODE=ON &&
        make &&
        sudo make install
        ;;
      esac ;

  # test
  - admsXml -h

